import Head from "next/head";
import { GetStaticProps } from 'next';
import { client } from "@/lib/client";

export type ArticleContents = {
  body?: string;
  id: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  revisedAt: string;
  tagman: any;
  tags: any;
  title: string;
}

export type ArticlesResponse = {
  contents: ArticleContents[];
  totalCount: number;
  offset: number;
  limit: number;
};

interface HomeProps {
  articlesResponse: ArticlesResponse;
}

const Home: React.FC<HomeProps> = ({ articlesResponse }) => {
  console.log(articlesResponse);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Articles14</h1>
        <ul>
          {articlesResponse.contents.map((article) => (
            <li key={article.id}>
              <h2>{article.title}</h2>
              <p>{article.createdAt}</p>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  // APIエンドポイントからデータを直接取得
  const articlesResponse = await client.get({
    endpoint: "articles",
    queries: { limit: 10, orders: "-publishedAt" },
  });

  return {
    props: {
      articlesResponse,
    },
  };
};

export default Home;